spring.application.name=gateway-service
server.port=8080

# Rota: Auth Service
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${SERVICES_AUTH_URL:http://localhost:8084}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/auth/**

# Rota: Segurados Service
spring.cloud.gateway.server.webflux.routes[1].id=segurados-service
spring.cloud.gateway.server.webflux.routes[1].uri=${SERVICES_SEGURADOS_URL:http://localhost:8085}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/segurados/**

# Rota: Apolices Service
spring.cloud.gateway.server.webflux.routes[2].id=apolices-service
spring.cloud.gateway.server.webflux.routes[2].uri=${SERVICES_APOLICES_URL:http://localhost:8086}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/apolices/**

# Rota: Sinistros Service
spring.cloud.gateway.server.webflux.routes[3].id=sinistros-service
spring.cloud.gateway.server.webflux.routes[3].uri=${SERVICES_SINISTROS_URL:http://localhost:8087}
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/sinistros/**

# Allowed Methods (Mapeados como lista indexada)
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[0]=GET
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[1]=POST
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[2]=PUT
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[3]=PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[4]=DELETE
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods[5]=OPTIONS

# Headers e Credentials
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers[0]=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOriginPatterns[0]=*

jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXNlY3VyZS1hbmQtc3VmaWNpZW50bHktbG9uZy1zZWNyZXQta2V5LWZvci1qd3QtMjU2LWJpdHM=}
management.endpoints.web.exposure.include=health

# Configuração Swagger Aggregator
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/api/v1/auth/v3/api-docs
springdoc.swagger-ui.urls[1].name=Segurados Service
springdoc.swagger-ui.urls[1].url=/api/v1/segurados/v3/api-docs
springdoc.swagger-ui.urls[2].name=Apolices Service
springdoc.swagger-ui.urls[2].url=/api/v1/apolices/v3/api-docs
springdoc.swagger-ui.urls[3].name=Sinistros Service
springdoc.swagger-ui.urls[3].url=/api/v1/sinistros/v3/api-docs
springdoc.swagger-ui.persist-authorization=true