export type StatusSinistro = 'REGISTRADO' | 'EM_ANALISE' | 'AGUARDANDO_DOCUMENTOS' | 'APROVADO' | 'REJEITADO' | 'PAGO';

export type TipoSinistro = 'COLISAO' | 'ROUBO_FURTO' | 'INCENDIO' | 'DANO_A_TERCEIRO' | 'ALAGAMENTO' | 'QUEBRA_DE_VIDRO' | 'OUTROS';

export type TipoDocumento = 'BOLETIM_OCORRENCIA' | 'FOTO_DANO' | 'NOTA_FISCAL' | 'LAUDO_TECNICO' | 'CNH' | 'DOCUMENTO_VEICULO' | 'OUTROS';

export type StatusApolice = 'ATIVA' | 'CANCELADA' | 'EXPIRADA' | 'SUSPENSA';

export type TipoSeguro = 'AUTO' | 'RESIDENCIAL' | 'VIDA' | 'PATRIMONIAL' | 'EMPRESARIAL';

export type TipoPessoa = 'PF' | 'PJ';

export type TipoCobertura = 'COLISAO' | 'ROUBO_FURTO' | 'INCENDIO_VEICULO' | 'DANO_A_TERCEIRO' | 'QUEBRA_DE_VIDRO'
    | 'INCENDIO_RESIDENCIAL' | 'DANOS_ELETRICOS' | 'ROUBO_BENS' | 'ALAGAMENTO' | 'MORTE' | 'INVALIDEZ_PERMANENTE'
    | 'DOENCA_GRAVE' | 'DANO_EQUIPAMENTO' | 'LUCROS_CESSANTES' | 'RESPONSABILIDADE_CIVIL' | 'OUTROS';

export type PapelUsuario = 'ADMIN' | 'ANALISTA' | 'GESTOR';