spring.application.name=sinistros-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sinistros_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:insurtech}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:insurtech}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.port=8087

springdoc.swagger-ui.path=/swagger-ui.html

services.segurados.url=http://localhost:8085
services.apolices.url=http://localhost:8086